export const FROALA_BUTTONS = [
  'bold',
  'italic',
  'underline',
  'strikeThrough',
  'fontSize',
  'textColor',
  'backgroundColor',
  'clearFormatting',
  'alignLeft',
  'alignCenter',
  'alignRight',
  'videoSnapshot',
  'insertLink',
  'insertImage',
  'insertVideo',
  'insertTable',
  'formatOLSimple',
  'paragraphFormat',
  'indent',
  'quote',
  'emoticons',
  'embedly',
  'insertFile',
  'insertHR',
];

export const FROALA_PLUGINS = [
  'table',
  'spell',
  'quote',
  'save',
  'quickInsert',
  'paragraphFormat',
  'paragraphStyle',
  'help',
  'draggable',
  'align',
  'link',
  'lists',
  'file',
  'fontSize',
  'image',
  'emoticons',
  'url',
  'video',
  'embedly',
  'colors',
  'entities',
  'imageTUI',
];

export const NOTE_TYPE = {
  MARKDOWN: 0,
  CANVAS: 1,
};

export const NOTE_PLUS_TYPE = {
  DEFAULT: 0,
  RECORD: 1,
  SEARCH: 2,
};

export const Colors = {
  Gray: '#f1f2f5',
  Gray0: '#ebecf0',
  Gray1: '#979797',
  Gray2: '#6b6b6b',
  Gray3: '#dfdfdf',
  Blue: '#3055fe',
  Blue1: '#0098f7',
  Blue2: '#E0EAFF',
  Blue3: '#4669fc',
  Blue4: '#00A4E1',
  Blue5: '#A1B6DE',
  Red: '#e31514',
  Red1: '#FF3D33',
  Yellow: '#FFCC17',
  Green: '#54BF00',
  Purple: '#262261',
  Black: '#000000',
  Black1: '#272727',
  Black2: '#000000b5',
  Black3: '#333333',
  White: '#ffffff',
  White1: '#F3F4F5',
  Transparent: 'transparent',
};
