export const FROALA_TEXT_BUTTONS = [
  'bold',
  'italic',
  'underline',
  'strikeThrough',
  'subscript',
  'superscript',
  'fontFamily',
  'fontSize',
  'textColor',
  'backgroundColor',
  'inlineClass',
  'inlineStyle',
  'clearFormatting',
];
export const FROALA_PARAGRAPH_BUTTONS = [
  'alignLeft',
  'alignCenter',
  'formatOLSimple',
  'alignRight',
  'alignJustify',
  'formatOL',
  'formatUL',
  'paragraphFormat',
  'paragraphStyle',
  'lineHeight',
  'outdent',
  'indent',
  'quote',
];
export const FROALA_RICH_BUTTONS = [
  'insertLink',
  'insertImage',
  'insertVideo',
  'insertTable',
  'emoticons',
  'fontAwesome',
  'specialCharacters',
  'embedly',
  'insertFile',
  'insertHR',
];
export const FROALA_MISC_BUTTONS = [
  'videoSnapshot',
  'undo',
  'redo',
  'fullscreen',
  'print',
  'getPDF',
  'spellChecker',
  'selectAll',
  'html',
  'help',
];
export const FROALA_PLUGINS = [
  'table',
  'spell',
  'quote',
  'save',
  'quickInsert',
  'paragraphFormat',
  'paragraphStyle',
  'help',
  'draggable',
  'align',
  'link',
  'lists',
  'file',
  'image',
  'emoticons',
  'url',
  'video',
  'embedly',
  'colors',
  'entities',
  'inlineClass',
  'inlineStyle',
  'imageTUI',
];

export const NOTE_TYPE = {
  MARKDOWN: 0,
  CANVAS: 1,
  SCREEN_CANVAS: 2,
};
