export const timeArr: string[] = [
  '00:00',
  '00:05',
  '00:10',
  '00:15',
  '00:20',
  '00:25',
  '00:30',
  '00:35',
  '00:40',
  '00:45',
  '00:50',
];
export const imageArr: string[] = [
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000000.jpg',
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000001.jpg',
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000002.jpg',
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000003.jpg',
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000004.jpg',
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000005.jpg',
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000006.jpg',
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000007.jpg',
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000008.jpg',
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000009.jpg',
  'https://service-video-storage.s3.ap-northeast-2.amazonaws.com/test_hls/Default/Thumbnails/test_hls.0000010.jpg',
];
